### ISSUE TITLE
Readme 描述有问题

### ISSUE THREAD

**Issue by imfht** [Trim21/sdu_bkjws#4]
Readme 中讲到
> 因为所用到的依赖beautifulsoup4不支持python2,所以本项目不会支持python2

理由不成立，[bs4的文档](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)中讲到
> The examples in this documentation should work the same way in Python 2.7 and Python 3.2.

pypi 中的包也是提供了 py2支持的
![image](https://user-images.githubusercontent.com/15059493/29993629-3fbfc474-8fef-11e7-95de-e8cb31c53bbe.png)

建议换一个不兼容 py2的理由 `~`

**Comment by imfht** [comment]
# 另
是否考虑出云抢课的Web 服务？

**Comment by trim21** [comment]
哇，终于被人发现了（

选课部分的逻辑还没分析过，这部分功能还没加上…
云抢课什么的可能会加在个人网站上，Trim21/sdu-exam-result

**Comment by trim21** [comment]
[Trim21/sdu-exam-result](https://github.com/Trim21/sdu-exam-result)

**Comment by trim21** [comment]
顺便 教务系统是不是上不去了…
